name: Push trigger for inji-vci-client

on:
  push:
    branches:
    - main
    - develop
    - qa-develop
    - 'release-**'
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
    - main
    - develop
    - qa-develop
    - 'release-**'

jobs:
  build-kotlin:
    uses: mosip/kattu/.github/workflows/gradle-build.yml@master
    with:
      SERVICE_LOCATION: kotlin
      JAVA_VERSION: 17
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_INJI_TEAM }}

  build-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Run js tests
        run: |
          cd js
          npm ci
          npm test

      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,author,commit,workflow,job 
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_INJI_TEAM }}
        if: "${{ github.event_name != 'pull_request' && failure() }}"

  sonar_analysis:
    needs: build-kotlin
    if: "${{  github.event_name != 'pull_request' }}"
    uses: mosip/kattu/.github/workflows/gradlew-sonar-analysis.yml@master-java21
    with:
      SERVICE_LOCATION: kotlin/vci-client
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_ORGANIZATION: ${{ secrets.ORG_KEY }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_INJI_TEAM }}
